# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 领京豆-升级赚豆

on:
    workflow_dispatch:
    schedule:
        - cron: "3 16 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_bean_home

jobs:
    build:
        runs-on: ubuntu-latest
        # if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: npm install
              run: |
                  npx npm@6 install
            - name: "运行【领京豆-升级赚豆】"
              run: |
                  node jd_bean_home.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  JD_USER_AGENT: ${{ github.event.client_payload.JD_USER_AGENT || secrets.JD_USER_AGENT }} 
                  PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }} 
